version: '3.8'

services:
  bootnode:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bootnode
    ports:
      - "38960:38960"
    volumes:
      - ./bootnode.key:/app/bootnode.key:ro
    command: >
      subnet.cli.run_node  --private_key_path /app/bootnode.key  --port 38960  --subnet_id 1  --no_blockchain_rpc  --is_bootstrap

  node-alith:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-alith
    ports:
      - "38961:38961"
    volumes:
      - ./alith.key:/app/alith.key:ro
    command: >
      subnet.cli.run_node  --private_key_path /app/alith.key  --port 38961  --bootstrap /dns4/bootnode/tcp/38960/p2p/12D3KooWLGmub3LXuKQixBD5XwNW4PtSfnrysYzqs1oj19HxMUCF  --subnet_id 1  --subnet_node_id 1  --no_blockchain_rpc
    depends_on:
      - bootnode

  node-baltathar:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-baltathar
    ports:
      - "38962:38962"
    volumes:
      - ./baltathar.key:/app/baltathar.key:ro
    command: >
      subnet.cli.run_node  --private_key_path /app/baltathar.key  --port 38962  --bootstrap /dns4/bootnode/tcp/38960/p2p/12D3KooWLGmub3LXuKQixBD5XwNW4PtSfnrysYzqs1oj19HxMUCF  --subnet_id 1  --subnet_node_id 2  --no_blockchain_rpc
    depends_on:
      - bootnode

  node-charleth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-charleth
    ports:
      - "38963:38963"
    volumes:
      - ./charleth.key:/app/charleth.key:ro
    command: >
      subnet.cli.run_node  --private_key_path /app/charleth.key  --port 38963  --bootstrap /dns4/bootnode/tcp/38960/p2p/12D3KooWLGmub3LXuKQixBD5XwNW4PtSfnrysYzqs1oj19HxMUCF  --subnet_id 1  --subnet_node_id 3  --no_blockchain_rpc
    depends_on:
      - bootnode

  node-dorothy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-dorothy
    ports:
      - "38964:38964"
    volumes:
      - ./dorothy.key:/app/dorothy.key:ro
    command: >
      subnet.cli.run_node  --private_key_path /app/dorothy.key  --port 38964  --bootstrap /dns4/bootnode/tcp/38960/p2p/12D3KooWLGmub3LXuKQixBD5XwNW4PtSfnrysYzqs1oj19HxMUCF  --subnet_id 1  --subnet_node_id 4  --no_blockchain_rpc
    depends_on:
      - bootnode

  node-ethan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-ethan
    ports:
      - "38965:38965"
    volumes:
      - ./ethan.key:/app/ethan.key:ro
    command: >
      subnet.cli.run_node  --private_key_path /app/ethan.key  --port 38965  --bootstrap /dns4/bootnode/tcp/38960/p2p/12D3KooWLGmub3LXuKQixBD5XwNW4PtSfnrysYzqs1oj19HxMUCF  --subnet_id 1  --subnet_node_id 5  --no_blockchain_rpc
    depends_on:
      - bootnode
