# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: subnet/protocols/pb/mock_protocol.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'subnet/protocols/pb/mock_protocol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'subnet/protocols/pb/mock_protocol.proto\x12\x10mock_protocol.pb\"\xb2\x01\n\x13MockProtocolMessage\x12K\n\x04type\x18\x01 \x02(\x0e\x32=.mock_protocol.pb.MockProtocolMessage.MockProtocolMessageType\x1a!\n\x04Peer\x12\n\n\x02id\x18\x01 \x02(\x0c\x12\r\n\x05\x61\x64\x64rs\x18\x02 \x03(\x0c\"+\n\x17MockProtocolMessageType\x12\x10\n\x0cTASK_REQUEST\x10\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'subnet.protocols.pb.mock_protocol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOCKPROTOCOLMESSAGE']._serialized_start=62
  _globals['_MOCKPROTOCOLMESSAGE']._serialized_end=240
  _globals['_MOCKPROTOCOLMESSAGE_PEER']._serialized_start=162
  _globals['_MOCKPROTOCOLMESSAGE_PEER']._serialized_end=195
  _globals['_MOCKPROTOCOLMESSAGE_MOCKPROTOCOLMESSAGETYPE']._serialized_start=197
  _globals['_MOCKPROTOCOLMESSAGE_MOCKPROTOCOLMESSAGETYPE']._serialized_end=240
# @@protoc_insertion_point(module_scope)
